### ISSUE TITLE
wwwroot directroy size is increasing massively

### ISSUE THREAD

**Issue by adityakanungo05** [DNNCommunity/DNNCommunity.Home#3]
In Azure web app, wwwroot directroy size is increasing massively. As I mentioned in \site\wwwroot\Install\Temp folder which stores the extension backup is carrying very large size. Is it safe to delete the files in temp folder, will it affect in anyway to my live website?
Please respond as soon as possible.
Thank you.

**Comment by valadas** [comment]
In theory that folder is only used while a module is in the process of installing and it should be fine to delete.
However, I would recommend taking a backup first just in case.

**Comment by WillStrohl** [comment]
We delete the `Temp` folder regularly as part of our standard maintenance.   

https://github.com/UpendoVentures/Upendo-Dnn-Prompt/wiki/delete-tempfolder
